# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

container: mcr.microsoft.com/dotnet/core/sdk:3.1-buster

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'restore'
    arguments: '--force-evaluate'
  displayName: 'Restore NuGet Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    projects: '**/Projects/Server/Server.csproj'
  displayName: 'Build Server'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    projects: '**/Projects/UOContent/UOContent.csproj'
  displayName: 'Build UO Content'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  displayName: 'Test'
