name: 'Build'

trigger:
- master

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
- job: BuildWindows
  displayName: 'Windows Server 2019'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: NuGetAuthenticate@0
  - script: dotnet restore --force-evaluate
    displayName: 'Restore NuGet Packages'
  - script: dotnet build -c $(buildConfiguration) --no-restore Projects/Server/Server.csproj
    displayName: 'Build Server'
  - script: dotnet build -c $(buildConfiguration) --no-restore Projects/UOContent/UOContent.csproj
    displayName: 'Build UO Content'
  - script: dotnet test --no-restore
    displayName: 'Test'

- job: BuildLinux
  strategy:
    matrix:
      'Debian 10':
        containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      'Ubuntu 18':
        containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
      # 'Ubuntu 20':
      #   containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-focal

  displayName: Linux

  pool:
    vmImage: 'ubuntu-latest'

  container: $[ variables['containerImage'] ]

  steps:
  - task: NuGetAuthenticate@0
  - script: dotnet restore --force-evaluate
    displayName: 'Restore NuGet Packages'
  - script: dotnet build -c $(buildConfiguration) --no-restore Projects/Server/Server.csproj
    displayName: 'Build Server'
  - script: dotnet build -c $(buildConfiguration) --no-restore Projects/UOContent/UOContent.csproj
    displayName: 'Build UO Content'
  - script: dotnet test --no-restore
    displayName: 'Test'
