name: 'Build'

trigger:
- master

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
- job: BuildWindows
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'restore'
      arguments: '--force-evaluate'
    displayName: 'Restore NuGet Packages'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '-c $(buildConfiguration)'
      projects: '**/Projects/Server/Server.csproj'
    displayName: 'Build Server'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '-c $(buildConfiguration)'
      projects: '**/Projects/UOContent/UOContent.csproj'
    displayName: 'Build UO Content'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
    displayName: 'Test'

- job: BuildMacOS
  pool:
    vmImage: 'macos-latest'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'restore'
      arguments: '--force-evaluate'
    displayName: 'Restore NuGet Packages'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '-c $(buildConfiguration)'
      projects: '**/Projects/Server/Server.csproj'
    displayName: 'Build Server'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '-c $(buildConfiguration)'
      projects: '**/Projects/UOContent/UOContent.csproj'
    displayName: 'Build UO Content'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
    displayName: 'Test'

- job: BuildLinux
  strategy:
    matrix:
      debian10:
        containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      ubuntu18:
        containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
      # ubuntu20:
      #   containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-focal

  pool:
    vmImage: 'ubuntu-latest'

  container: $[ variables['containerImage'] ]

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'restore'
      arguments: '--force-evaluate'
    displayName: 'Restore NuGet Packages'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '-c $(buildConfiguration)'
      projects: '**/Projects/Server/Server.csproj'
    displayName: 'Build Server'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '-c $(buildConfiguration)'
      projects: '**/Projects/UOContent/UOContent.csproj'
    displayName: 'Build UO Content'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
    displayName: 'Test'
