name: 'Build'

trigger:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
- job: BuildWindows
  displayName: 'Windows Server 2019'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 5'
    inputs:
      packageType: sdk
      version: '5.0.102'
  - task: NuGetAuthenticate@0
  - script: ./publish.cmd Release $(os)
    displayName: 'Build'
  - script: dotnet test --no-restore
    displayName: 'Test'

- job: BuildLinux
  strategy:
    matrix:
      'CentOS 8':
        containerImage: modernuo/centos-net5:8
        os: centos.8-x64
      'CentOS 7':
        containerImage: centos:7
        os: centos.7-x64
      'Debian 10':
        containerImage: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
        os: debian.10-x64
      # 'Debian 11':
      #   containerImage: amd64/buildpack-deps:bullseye
      #   os: debian.11-x64
      'Ubuntu 20':
        containerImage: mcr.microsoft.com/dotnet/sdk:5.0-focal
        os: ubuntu.20.04-x64

  displayName: Linux

  pool:
    vmImage: 'ubuntu-latest'

  container: $[ variables['containerImage'] ]

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 5'
    inputs:
      packageType: sdk
      version: '5.0.102'
  - task: NuGetAuthenticate@0
  - script: ./publish.cmd Release $(os)
    displayName: 'Build'
  - script: dotnet test --no-restore
    displayName: 'Test'
