name: 'Build'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

strategy:
  matrix:
    win2019:
      containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1
    debian10:
      containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
    ubuntu18:
      containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
    ubuntu20:
      containerImage: mcr.microsoft.com/dotnet/core/sdk:3.1-focal

container: $[ variables['containerImage'] ]

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'restore'
    arguments: '--force-evaluate'
  displayName: 'Restore NuGet Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    projects: '**/Projects/Server/Server.csproj'
  displayName: 'Build Server'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    projects: '**/Projects/UOContent/UOContent.csproj'
  displayName: 'Build UO Content'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  displayName: 'Test'
