services:
  modernuo:
    build:
      context: .
      args:
        OS: "${OS:-linux}"
        ARCH: "${ARCH:-amd64}"
    environment:
      UO_DIRECTORY: ${UO_DIRECTORY:-/bin/UO}
    ports:
      - "2593:2593"
      - "12000:12000"
    volumes:
      - "./Distribution/Configuration:/bin/modernuo/Configuration"
      - "./Distribution/Data:/bin/modernuo/Data"
      - "./Distribution/Saves:/bin/modernuo/Saves"
      # see the example in the DOCKER.md file to understand this volume
      - "$UO_DIRECTORY:/bin/UO"
