
# Project
site_name: ModernUO
site_author: Kamron Batman
site_url: https://modernuo.com

# Repository
repo_name: modernuo/modernuo
repo_url: https://github.com/modernuo/modernuo
site_description: Ultima Online for the modern era!
copyright: Copyright &copy; 2020 ModernUO Dev Team
theme:
  name: material
  icon:
    logo: modernuo/logo
  custom_dir: docs/overrides
  features:
    - tabs
    - instant
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

# Pages
nav:
  - Home: 'index.md'
  - Getting started:
    - Installation: getting-started.md
