receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317

exporters:
    prometheus:
        endpoint: "0.0.0.0:8889"

    debug:

processors:
    batch:

extensions:
    health_check:

service:
    extensions: [health_check]
    pipelines:
       metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, prometheus]
