name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    name: Build (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ubuntu:jammy
            name: Ubuntu 22
            packageManager: apt
    steps:
      - name: Install Prerequisites using apt
        run: apt-get update -y && apt-get install -y curl libicu-dev libdeflate-dev zstd libargon2-dev
        if: ${{ matrix.packageManager == 'apt' }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: ./publish.cmd Release
      - name: Test
        run: dotnet test --no-restore
