name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15
    - name: Restore NuGet Packages
      run: dotnet restore --force-evaluate
    - name: Build Server
      run: dotnet build -c Release -f net5.0 --no-restore Projects/Server/Server.csproj
    - name: Build UO Content
      run: dotnet build -c Release -f net5.0 --no-restore Projects/UOContent/UOContent.csproj
    - name: Test
      run: dotnet test --no-restore -f net5.0
