name: Create Release

on:
  repository_dispatch:
    types: [release]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install NGBV
      uses: dotnet/nbgv@master
      id: nbgv
    - name: Conventional Changelog
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        output-file: false
        skip-version-file: true
        skip-commit: true
    - uses: dev-drprasad/delete-tag-and-release@v0.1.3
      with:
        delete_release: true
        tag_name: 0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        body: ${{ steps.changelog.outputs.clean_changelog }}
        tag_name: ${{ steps.nbgv.outputs.Version }}
        release_name: ${{ steps.nbgv.outputs.Version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
