name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'Release')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [win, ubuntu.16.04, ubuntu.18.04, ubuntu.20.04, debian.9, debian.10, centos.7, centos.8, osx]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - uses: dotnet/nbgv@master
      id: nbgv
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.nbgv.outputs.Version }}
        release_name: ${{ steps.nbgv.outputs.Version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Windows
      run: ./publish.cmd win core Release
    - name: Create Artifact (${{ matrix.os }})
      run: rm -rf ./Projects/*/bin && rm -rf ./Projects/*/obj && zip -9 -r modernuo-${{ matrix.os }}-x64-${{ steps.nbgv.outputs.Version }}.zip ./*
    - name: Upload Build (${{ matrix.os }})
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./modernuo-${{ matrix.os }}-x64-${{ steps.nbgv.outputs.Version }}.zip
        asset_name: modernuo-${{ matrix.os }}-x64-${{ steps.nbgv.outputs.Version }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
