name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore NuGet Packages
      run: dotnet restore --force-evaluate
    - name: Build Server
      run: dotnet build -c Release --no-restore Projects/Server/Server.csproj
    - name: Build UO Content
      run: dotnet build -c Release --no-restore Projects/UOContent/UOContent.csproj
    - name: Test
      run: dotnet test --no-restore
