name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401
      - name: Install DotNet Format
        run: dotnet tool install -g dotnet-format
      - name: Restore NuGet Packages
        run: dotnet restore --force-evaluate
      - name: Lint
        run: dotnet format --check

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Restore NuGet Packages
      run: dotnet restore --force-evaluate
    - name: Build Server
      run: dotnet build -c Release -f netcoreapp3.1 --no-restore Projects/Server/Server.csproj
    - name: Build UO Content
      run: dotnet build -c Release -f netcoreapp3.1 --no-restore Projects/UOContent/UOContent.csproj
    - name: Test
      run: dotnet test --no-restore -f netcoreapp3.1
