name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Build ZLib
      run: dotnet build -c Release Projects/ZLib/ZLib.csproj
    - name: Pack ZLib NuGet
      if: steps.zlib-cache.outputs.cache-hit != 'true'
      run: dotnet pack -c Release -o packages Projects/ZLib/ZLib.csproj
    - name: Build Argon2
      run: dotnet build -c Release Projects/Argon2/Argon2.csproj
    - name: Pack Argon2 NuGet
      if: steps.argon2-cache.outputs.cache-hit != 'true'
      run: dotnet pack -c Release -o packages Projects/Argon2/Argon2.csproj
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build -c Release Projects/Server/Server.csproj
    - name: Build UO Content
      run: dotnet build -c Release Projects/UOContent/UOContent.csproj
    - name: Test Server
      run: dotnet test -r ${{ matrix.rid }} Projects/Server.Tests/Server.Tests.csproj
    - name: Test UO Content
      run: dotnet test -r ${{ matrix.rid }} Projects/UOContent.Tests/UOContent.Tests.csproj
