name: Publish Docker Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup BuildKit
      uses: docker/setup-buildx-action@v3

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: modernuo/modernuo:latest,modernuo/modernuo:${{ inputs.version }}
