name: Publish Docker Image

on:
  repository_dispatch:
    types: [release]
  workflow_dispatch:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup BuildKit
      uses: docker/setup-buildx-action@v3

    - name: Get Revision
      id: get_revision
      run: |
        echo "short_sha_7=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_OUTPUT"

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: modernuo/modernuo:latest,modernuo/modernuo:${{ steps.get_revision.outputs.short_sha_7 }}
