name: Updates Commands

on:
  repository_dispatch:
    types: [commands]
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/commands
          clean: false
          force: false
          git-config-name: Commands-Update-Action
